### ISSUE TITLE
The black woman

### ISSUE THREAD

**Issue by PyGamma** [ASKnet-Open-Training/Womanhood-in-poetry#1]
Let someone create a poem about the black woman describing how virtuous and hard working she is.
Preferably a lady can take this issue but of course this should not stop the gentlemen from claiming this issue as well, before you start please claim this issue in the comments section so that you can be assign to it

**Comment by gibertgibs** [comment]
I would love to but then I need a female challenger.....Yine Yenki can tell me who this lady will be....She was there for the audition show....Or even any lady.

**Comment by PyGamma** [comment]
This is good so far, let's now continue to build it
